In [1]:
import numpy as np

In [15]:
arr_st = np.array([[20,-9,-40],[10,0,-1],[7,6,34]])
print(arr_st)

[[ 20  -9 -40]
 [ 10   0  -1]
 [  7   6  34]]


max()

In [16]:
print(np.max(arr_st))
print(np.max(arr_st,axis=0)) #max value along every column
print(np.max(arr_st,axis=1)) #max value along every row

34
[20  6 34]
[20 10 34]


min()

In [17]:
print(np.min(arr_st))
print(np.min(arr_st,axis=0)) #min value along every column
print(np.min(arr_st,axis=1)) #min value along every row

-40
[  7  -9 -40]
[-40  -1   6]


Sum

In [18]:
print(np.sum(arr_st))
print(np.sum(arr_st,axis=0))
print(np.sum(arr_st,axis=1))

27
[37 -3 -7]
[-29   9  47]


argmax()

In [19]:
#tells the index value of the max element in the matrix
print(np.argmax(arr_st))
print(np.argmax(arr_st,axis=0))
print(np.argmax(arr_st,axis=1))



8
[0 2 2]
[0 0 2]


Same goes for argmin()

In [20]:
print(np.argmin(arr_st))
print(np.argmin(arr_st,axis=0))
print(np.argmin(arr_st,axis=1))

2
[2 0 0]
[2 2 1]


np.around()

In [21]:
#tells the round off value of the elements in th array
arr_ro = np.array([3.09,5.96,7.35])
print(np.around(arr_ro))

[3. 6. 7.]


In [25]:
# we can also decide the number of decimal places to be left 
arr_ro2 = np.array([3.14568739,5.962848535,7.355678])
print(np.around(arr_ro2,decimals=3))

[3.146 5.963 7.356]


Floor and Ceil

In [29]:
#it is also like around() but the rounding off is done differently 
a = np.array([-1.7,-4.2,4.6,-0.87])
print(np.floor(a)) # rounds of to the adjecent lower value of the element
print(np.ceil(a)) # rounds of to the adjecent higher value of the element

[-2. -5.  4. -1.]
[-1. -4.  5. -0.]


copy and view

In [31]:
# copy allows for making a litral copy of an array 
# and the changes done to the copy will not affect the original array 
arr = np.array([3,4,5,6,7])
x = arr.copy()
print(x)
x[0] = 56
print("this is x: ",x)
print("this is original array: ",arr)

[3 4 5 6 7]
this is x:  [56  4  5  6  7]
this is original array:  [3 4 5 6 7]


In [33]:
# view allos to make a variable which show the mirror image array
# any changes done to th eview variable is done to the original
arr = np.array([3,4,5,6,7])
x = arr.view()
print(x)
x[0] = 56
print("this is x: ",x)
print("this is original array: ",arr)
arr[3] = 23
print("x after change in arr: ",x)
print("arr after the change: ",arr)

[3 4 5 6 7]
this is x:  [56  4  5  6  7]
this is original array:  [56  4  5  6  7]
x after change in arr:  [56  4  5 23  7]
arr after the change:  [56  4  5 23  7]


Iteration

In [35]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr3 = np.array([[[1,2,3],
                  [4,5,6]],
                  [[7,8,9],
                  [10,11,12]]])

In [36]:
for i in arr1:
    print(i)

1
2
3
4
5


In [38]:
for i in arr2:
    print(i)
for i in arr2[1]:
    print(i)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
5
6
7
8


In [48]:
for i in arr3[1]:
    print(i)

[7 8 9]
[10 11 12]
