In [2]:
import random
import numpy as np
import time

In [4]:
a = np.random.rand(1000000000)
# this finction allows for 1000000000 values 
# between 0 and 1 to formed and added as an array in a
print(a)

[0.47108528 0.07414149 0.08532207 ... 0.76189681 0.85917676 0.49684137]


In [5]:
# list
# here we are finding the mean of the very big list above using 
# only list functionalities
start = time.time()
mean_list = sum(a)/len(a)
print(time.time() - start)

72.61893582344055


In [6]:
# numpy
# here we are finding the mean of the very big list above using 
# numpy functionalities, which is considered to be much much faster

start = time.time()
mean_np = np.mean(a)
print(time.time()-start)

1.381807804107666


As we can clearly see that there is a difference between the computing time taken, and Numpy allows us to deal with them much faster

In [7]:
np.__version__

'1.26.4'

Operations in numpy

Initialising an Array using numpy

In [9]:
# 0-D array
arr = np.array([4])
print(arr)

[4]


In [ ]:
list = [1,2,3,4,5,6,7,8,9,10]

In [10]:
# 1-D Array
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [21]:
# 2-D array
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr1)
# matrix is a good example of 2-D array

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [22]:
# 3-D array
arr2 = np.array([
    [
        [1,2,3,4],
        [5,6,7,8]
    ],
    [
        [8,7,6,5],
        [4,3,2,1]
    ]])
print(arr2)


type(arr2)

[[[1 2 3 4]
  [5 6 7 8]]

 [[8 7 6 5]
  [4 3 2 1]]]


numpy.ndarray

We can even use tuples to store the data

In [18]:
arr = np.array((1,2,3,4))
print(arr)

[1 2 3 4]
1


In [23]:
# ndim fucntion allows us to know the dimentions of an array
print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)

1
2
3


we can make an array of any dimension using numpy, here is how:

"ndmin" attribute lets us decide what dimension we want to give to an array

In [25]:
arr = np.array([1,2,3,4,5],ndmin =3)
print(arr)
print(arr.ndim)

[[[1 2 3 4 5]]]
3


In [33]:
arr10 = np.array([1,2,3,4,5],ndmin =10)
print(arr10)
print(arr10.ndim)

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]
10


"shape" attribute tells us about the size of the array

In [31]:
arr = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
])
arr.shape

(3, 5)

In [35]:
#shape of a 3-D array
print(arr2.shape)
#sahpe of a 10-D array
print(arr10.shape)

(2, 2, 4)
(1, 1, 1, 1, 1, 1, 1, 1, 1, 5)


"dtype" attribute tells about the type of data in the given data structure

In [41]:
arr_int = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
])
arr_str = np.array(['Keshav','Harsh','Pushkar','Akshay'])
print(arr_int.dtype) # 'int32' standes for integer
print(arr_str.dtype) #'<U7' stands for unicode of max size 7

int32
<U8


Even when arrays are homogeneous, ndarrays are hetergenous because in python the lists are heterogenous, numpy should not have any flaws

In [40]:
arr_new = np.array(['apple','mangoes','cherry', 9.9])
print(arr_new)
print(arr_new.dtype) 

['apple' 'mangoes' 'cherry' '9.9']
<U32


"size" attribute tells us about the number of elements in the data

In [57]:
arr= np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
])
print(arr.size)

15


np.size() function

In [58]:
#we can also get the number of rows or columns in an array
print(np.size(arr,0)) # 0 is specified for rows 
print(np.size(arr,1)) # 1 is specified for columns

3
5


"Itemsize" attribute tells us about the length of the single elements in byte or the amount of storage used to store a single element of an array 

In [61]:
print(arr.itemsize)

4


"nbytes" telss the total bytes

In [62]:
arr.nbytes

60