CRUD operations

create - c
read - r
update - u 
delete - d

In [2]:
import numpy as np

C - Create

In [4]:
#np.array()
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [10]:
# this for when we need an arraywith only zeroes as its values 
# np.zeros(size of array,datatype)
# by default the dtype of the zeroes int he array is Float
# but we can change it 
arr1 = np.zeros(10)
print(arr1)
arr2 = np.zeros((3,3),int)
print(arr2)
arr3 = np.zeros((5,3,3),int)
print(arr3)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [15]:
# np.ones(size of array, datatype)
# same as the last function it creates an array with only '1's as its values
arr_1 = np.ones((3,4))
print(arr_1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
# np.empty(size of array)
# creates array with garbage values
arr_nul = np.empty((2,2))
print(arr_nul)

[[6.23042070e-307 4.67296746e-307]
 [1.69121096e-306 4.81693045e-312]]


In [17]:
# np.full(size of array, value)
# it allows us to create a array of the shaoe we desire with all the values 
# that are same 

arr_full = np.full((4,4),5)
print(arr_full)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [20]:
# np.eye(number of ones needed) --> Idnetity matrix
# allows us to create an identity matrix
# the array needs to be a square matrix

arr_I = np.eye(8)
print(arr_I)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [21]:
# np.diag(array of values[])
# allows us to create a diagonal matrix
# we can put the values of the element in the diagonal
# in a array as aparameter for the function
arr_d = np.diag([1,2,3,4,5])
print(arr_d)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [25]:
# np.linspace(start,end,number of values) -- start and end values are included in the array 
# this function allows us to create a array with any number of values between 2 parameters 
# where two consequtive values will have same differences throughout the array
# data will be of float datatype by default


arr_l = np.linspace(10,100,10)
print(arr_l)
arr_l2 =np.linspace(0,10,20)
print(arr_l2)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [27]:
# np.random.rand(size of array)
# creates an array of the given size with random values
arr_rand = np.random.rand(3,4)
print(arr_rand)

[[0.44252576 0.3691182  0.16215375 0.88044121]
 [0.28339601 0.60150724 0.00751351 0.15929272]
 [0.04199342 0.06359506 0.95318352 0.13338255]]


In [32]:
# np.random.randint(start, end, size=(), datatype)
# creates an array with the size provided and the integer values are between [satrt, end)

arr_randint = np.random.randint(1,8,size=(1,5))
print(arr_randint)

[[7 5 1 5 7]]


In [39]:
# np.arange(start , end, step)
# returns evenly spaced values between a given interval [start,end)

arr_a = np.arange(1,10,2)
print(arr_a)

[1 3 5 7 9]


U -> Update

In [41]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])


In [42]:
# Indexing
#1D array
print(arr1[-1])
print(arr1[3])



5
4


In [46]:
arr3 = np.array([[[1,2,3],
                  [4,5,6]],
                  [[7,8,9],
                  [10,11,12]]])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [44]:
print(arr3[0,1,1])

5


Slicing

In [53]:
print(arr2)
print(arr2[1:2]) # here 1 and 2 are consider the indexs of rows 
# i.e. why we get the whole 2nd row
print(arr2[1,1:3]) # to get value inside a specific row add the index of 
# that row using  a ',' before the _:_ part

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[5 6 7 8]]
[6 7]


In [57]:
print(arr3)
#to access x = 0, y=1 i.e. [4,5,6]
print(arr3[0,1:])
#to access x=1,y=1,z=1,2 i.e. [11,12]
print(arr3[1,1,1:3])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[4 5 6]]
[11 12]


In [68]:
#quiz
#create and array of 3X4 dim and values between 10 to 500 and the values should be evenly distributed

arr_q = np.linspace(10,500,12)
arr_q = arr_q.reshape(3,4)
print(arr_q)


[[ 10.          54.54545455  99.09090909 143.63636364]
 [188.18181818 232.72727273 277.27272727 321.81818182]
 [366.36363636 410.90909091 455.45454545 500.        ]]


reshape function allows for the reshaping of an array to any dimension you want given the elements in the array are equal to what it should be in the desired array shape i.e. an array must have 12 elements to be reshaped into a 12X1, 3X4, 6X2 arrays. reshape function makes a copy of the array and makes changes to it , it doesn't change the original array.

In [70]:
#create a 7X9 matrix where all the elements are random

arr_r = np.random.rand(63).reshape(7,9)
print(arr_r)

[[4.34123585e-01 6.97347394e-01 3.98757818e-01 1.76046140e-01
  8.57022666e-01 1.76336419e-01 1.29293971e-01 8.11459657e-01
  7.73007903e-02]
 [4.69504790e-01 3.65815527e-02 1.04491307e-01 9.34070509e-01
  5.97423394e-01 5.68244599e-01 9.30523943e-01 8.78383213e-01
  9.62970456e-01]
 [7.97529622e-01 9.93329864e-01 9.04921140e-02 4.47921171e-01
  6.64191880e-01 6.35611582e-01 5.35759466e-01 7.63104741e-01
  1.60677013e-01]
 [5.88418932e-02 3.77140086e-01 2.69787348e-01 3.35385795e-01
  3.74096162e-01 5.43525444e-01 9.06705198e-01 3.09522213e-01
  4.01151158e-01]
 [3.52223877e-01 3.88981715e-02 1.64361906e-01 3.82962860e-01
  2.67472380e-01 1.51772811e-01 6.44284929e-01 5.25777425e-01
  1.74497300e-01]
 [1.97690869e-01 4.72898028e-01 3.01286061e-02 7.91866166e-01
  8.26981121e-02 5.80707254e-01 2.76714228e-01 9.46925095e-01
  8.56023706e-01]
 [4.50860396e-04 3.78688228e-02 7.14361232e-01 9.35877218e-01
  2.69902808e-01 6.50137813e-02 3.78949101e-01 3.77766424e-01
  3.22337514e-01]]


In [86]:
arr_new = arr2
print(arr_new)

arr2d = np.array([[15,16,17,18],[19,20,21,22],[23,24,25,26]])

#we need to merge these two 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [89]:
#we are using the np.append(array, values,axis=none)
#if we wnat to add a different array to another array they both need to have the same dimensions

print(np.append(arr_new,arr2d,axis=1))
print(np.append(arr_new,arr2d,axis=0))

[[ 1  2  3  4 15 16 17 18]
 [ 5  6  7  8 19 20 21 22]
 [ 9 10 11 12 23 24 25 26]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [15 16 17 18]
 [19 20 21 22]
 [23 24 25 26]]


In [90]:
arr_new+arr2d

array([[16, 18, 20, 22],
       [24, 26, 28, 30],
       [32, 34, 36, 38]])

In [91]:
arr_new +10

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [92]:
arr_new *2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])