In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2 = np.array([[11,12,13,14,15],[16,17,18,19,20]])

Mathematical Functions and Statistics

Addition -> adding two matrices and adding a element to a matrix

In [4]:
#adding two matrices
print(arr1+arr2)
#adding an element to a mtrix
print(arr2 +20)

[[12 14 16 18 20]
 [22 24 26 28 30]]
[[31 32 33 34 35]
 [36 37 38 39 40]]


In [5]:
#arr3 = np.array([1,2,3])  #adding this to arr1 will show an error
arr3 = np.array([1,2,3,4,5])

print(arr1+arr3) #since thwe size of the columns were the same 
#for both the array and the matrix the elements of arr3 were added to every row of arr1  


[[ 2  4  6  8 10]
 [ 7  9 11 13 15]]


In [6]:
arr3 =  np.array([[1],[2]]) #the size of rthe rows were same
print(arr1+arr3)

[[ 2  3  4  5  6]
 [ 8  9 10 11 12]]


Substraction

In [7]:
print(arr1+arr2)
print(arr1-10)


[[12 14 16 18 20]
 [22 24 26 28 30]]
[[-9 -8 -7 -6 -5]
 [-4 -3 -2 -1  0]]


Division

In [9]:
print(arr1/arr2)
print(arr1/4)

[[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333]
 [0.375      0.41176471 0.44444444 0.47368421 0.5       ]]
[[0.25 0.5  0.75 1.   1.25]
 [1.5  1.75 2.   2.25 2.5 ]]


Exponential

In [13]:
print(arr2)
print(arr1 ** arr2)
print(arr1 ** 2)


[[11 12 13 14 15]
 [16 17 18 19 20]]
[[          1        4096     1594323   268435456   452807053]
 [ -683606016 -2094633337           0  -400556711  1661992960]]
[[  1   4   9  16  25]
 [ 36  49  64  81 100]]


Multiplication

In [18]:
print(arr1,"\n\n",arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

 [[11 12 13 14 15]
 [16 17 18 19 20]]


In [19]:
#there are two types of prodeuct that can happen between two matrices
# cross product

arr1 * arr2

array([[ 11,  24,  39,  56,  75],
       [ 96, 119, 144, 171, 200]])

In [22]:
# dot product 
# the no. of columns of the first matrix must be equal to the no of rows of the second matrix
arr3 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
print(arr3.shape)

# these two methods allow us to get the dot multiplication of two matrices
print(np.dot(arr3,arr1))
print(np.matmul(arr3,arr1))

(5, 2)
[[ 13  16  19  22  25]
 [ 27  34  41  48  55]
 [ 41  52  63  74  85]
 [ 55  70  85 100 115]
 [ 69  88 107 126 145]]
[[ 13  16  19  22  25]
 [ 27  34  41  48  55]
 [ 41  52  63  74  85]
 [ 55  70  85 100 115]
 [ 69  88 107 126 145]]


Determinant

In [25]:
# to get a determinant of a matrix the matrix should a square matrix i.e. n=m
# we are going to use np.linalg module

arr_det = np.array([[-4,-10],[0,5]])
print(np.linalg.det(arr_det))

arr_det2 = np.array([[-4,-10,-6],[0,5,7],[-9,6,0]])
print(np.linalg.det(arr_det2))

-19.999999999999996
528.0


Inverse of a matrix

In [26]:
# if A is a mtrix it's inverse is (1/|det(A)|)*adj(A)
# ajd(A) is cof(A)^T

arr_inv = np.array([[-4,-10],[0,5]])
print(np.linalg.inv(arr_inv)) #prints the inverse of the  matrix

[[-0.25 -0.5 ]
 [ 0.    0.2 ]]


In [27]:
arr_inv.transpose()

array([[ -4,   0],
       [-10,   5]])

In [30]:
#adjoint of a matrix
arr_adj = np.linalg.inv(arr_inv)*abs(np.linalg.det(arr_inv))
print(arr_adj)

[[ -5. -10.]
 [  0.   4.]]


Reciprocal


In [32]:
arr_reci = np.array([[10,20],[30,40]])
print(arr_reci)

[[10 20]
 [30 40]]


In [ ]:
np.reciprocal()